Search.appendIndex(
    [
                {
            "fqsen": "\\termTemplates\\LiteralRegexTemplate",
            "name": "LiteralRegexTemplate",
            "summary": "Description\u0020of\u0020LiteralTemplate",
            "url": "classes/termTemplates-LiteralRegexTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\LiteralRegexTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-LiteralRegexTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\LiteralRegexTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-LiteralRegexTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\LiteralRegexTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-LiteralRegexTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\LiteralRegexTemplate\u003A\u003A\u0024lang",
            "name": "lang",
            "summary": "",
            "url": "classes/termTemplates-LiteralRegexTemplate.html#property_lang"
        },                {
            "fqsen": "\\termTemplates\\LiteralRegexTemplate\u003A\u003A\u0024datatype",
            "name": "datatype",
            "summary": "",
            "url": "classes/termTemplates-LiteralRegexTemplate.html#property_datatype"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate",
            "name": "LiteralTemplate",
            "summary": "Description\u0020of\u0020LiteralTemplate",
            "url": "classes/termTemplates-LiteralTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A\u0024lang",
            "name": "lang",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#property_lang"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A\u0024datatype",
            "name": "datatype",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#property_datatype"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeRegexTemplate",
            "name": "NamedNodeRegexTemplate",
            "summary": "",
            "url": "classes/termTemplates-NamedNodeRegexTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeRegexTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-NamedNodeRegexTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeRegexTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-NamedNodeRegexTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeTemplate",
            "name": "NamedNodeTemplate",
            "summary": "Description\u0020of\u0020AnyNamedNode",
            "url": "classes/termTemplates-NamedNodeTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-NamedNodeTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-NamedNodeTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate",
            "name": "NumericTemplate",
            "summary": "Description\u0020of\u0020AnyNamedNode",
            "url": "classes/termTemplates-NumericTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003AEQUALS",
            "name": "EQUALS",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#constant_EQUALS"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003AGREATER",
            "name": "GREATER",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#constant_GREATER"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003ALOWER",
            "name": "LOWER",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#constant_LOWER"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003AGREATER_EQUAL",
            "name": "GREATER_EQUAL",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#constant_GREATER_EQUAL"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003ALOWER_EQUAL",
            "name": "LOWER_EQUAL",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#constant_LOWER_EQUAL"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003AANY",
            "name": "ANY",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#constant_ANY"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024numericTypes",
            "name": "numericTypes",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_numericTypes"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024fn",
            "name": "fn",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_fn"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_value"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024matchMode",
            "name": "matchMode",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_matchMode"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024strict",
            "name": "strict",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_strict"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate",
            "name": "QuadTemplate",
            "summary": "Description\u0020of\u0020QuadTemplate",
            "url": "classes/termTemplates-QuadTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getSubject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getPredicate"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getObject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getGraph"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_subject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024predicate",
            "name": "predicate",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_predicate"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_object"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024graph",
            "name": "graph",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_graph"
        },                {
            "fqsen": "\\termTemplates\\RegexTemplate",
            "name": "RegexTemplate",
            "summary": "",
            "url": "classes/termTemplates-RegexTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\RegexTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-RegexTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\RegexTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-RegexTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\RegexTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-RegexTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\RegexTemplate\u003A\u003A\u0024regex",
            "name": "regex",
            "summary": "",
            "url": "classes/termTemplates-RegexTemplate.html#property_regex"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate",
            "name": "ValueTemplate",
            "summary": "Description\u0020of\u0020AnyNamedNode",
            "url": "classes/termTemplates-ValueTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AEQUALS",
            "name": "EQUALS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_EQUALS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ASTARTS",
            "name": "STARTS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_STARTS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AENDS",
            "name": "ENDS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_ENDS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ACONTAINS",
            "name": "CONTAINS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_CONTAINS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AGREATER",
            "name": "GREATER",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_GREATER"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ALOWER",
            "name": "LOWER",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_LOWER"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AGREATER_EQUAL",
            "name": "GREATER_EQUAL",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_GREATER_EQUAL"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ALOWER_EQUAL",
            "name": "LOWER_EQUAL",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_LOWER_EQUAL"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AANY",
            "name": "ANY",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_ANY"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A\u0024fn",
            "name": "fn",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#property_fn"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#property_value"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A\u0024matchMode",
            "name": "matchMode",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#property_matchMode"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode",
            "name": "BlankNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-BlankNode.html"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-BlankNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory",
            "name": "DataFactory",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AnamedNode\u0028\u0029",
            "name": "namedNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_namedNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AblankNode\u0028\u0029",
            "name": "blankNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_blankNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aliteral\u0028\u0029",
            "name": "literal",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_literal"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AdefaultGraph\u0028\u0029",
            "name": "defaultGraph",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_defaultGraph"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aquad\u0028\u0029",
            "name": "quad",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_quad"
        },                {
            "fqsen": "\\rdfInterface\\Dataset",
            "name": "Dataset",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-Dataset.html"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "Returns\u0020a\u0020new\u0020dataset\u0020being\u0020a\u0020union\u0020of\u0020the\u0020current\u0020one\u0020and\u0020the\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-Dataset.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "Returns\u0020a\u0020dataset\u0020being\u0020a\u0020symmetric\u0020difference\u0020of\u0020the\u0020current\u0020dataset\u0020and\nthe\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-Dataset.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020quad\u0028s\u0029\u0020to\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_delete"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AdeleteExcept\u0028\u0029",
            "name": "deleteExcept",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_deleteExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AforEach\u0028\u0029",
            "name": "forEach",
            "summary": "Iterates\u0020trough\u0020all\u0020quads\u0020replacing\u0020them\u0020with\u0020a\u0020callback\u0020result.",
            "url": "classes/rdfInterface-Dataset.html#method_forEach"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Checks\u0020if\u0020a\u0020given\u0020offset\u0020exists.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetExists"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Returns\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetGet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Assigns\u0020a\u0020new\u0020value\u0020to\u0020the\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Removes\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetUnset"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "Returns\u0020the\u0020current\u0020quad.",
            "url": "classes/rdfInterface-Dataset.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare",
            "name": "DatasetCompare",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-DatasetCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aevery\u0028\u0029",
            "name": "every",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_every"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Anone\u0028\u0029",
            "name": "none",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_none"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_any"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce",
            "name": "DatasetMapReduce",
            "summary": "Immutable\u0020edge\u0020processing\u0020methods",
            "url": "classes/rdfInterface-DatasetMapReduce.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_reduce"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph",
            "name": "DefaultGraph",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-DefaultGraph.html"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-DefaultGraph.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal",
            "name": "Literal",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Literal.html"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020literal.",
            "url": "classes/rdfInterface-Literal.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020literal\u0027s\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetLang\u0028\u0029",
            "name": "getLang",
            "summary": "Returns\u0020literal\u0027s\u0020language\u0020tag.",
            "url": "classes/rdfInterface-Literal.html#method_getLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetDatatype\u0028\u0029",
            "name": "getDatatype",
            "summary": "Returns\u0020literal\u0027s\u0020datatype.",
            "url": "classes/rdfInterface-Literal.html#method_getDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithValue\u0028\u0029",
            "name": "withValue",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithLang\u0028\u0029",
            "name": "withLang",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020lang\u0020tag\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithDatatype\u0028\u0029",
            "name": "withDatatype",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020with\u0020this\u0020one\u0020with\u0020datatype\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_LEXICAL_FORM",
            "name": "CAST_LEXICAL_FORM",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_LEXICAL_FORM"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_DATATYPE",
            "name": "CAST_DATATYPE",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_DATATYPE"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode",
            "name": "NamedNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-NamedNode.html"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-NamedNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parse"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parseStream"
        },                {
            "fqsen": "\\rdfInterface\\Quad",
            "name": "Quad",
            "summary": "Extends\u0020Term\u0020because\u0020of\u0020RDF\u002A",
            "url": "classes/rdfInterface-Quad.html"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "Null\u0020is\u0020not\u0020allowed\u0020to\u0020deal\u0020with\u0020the\u0020ambiguity\u0020between\u0020DefaultGraph\u0020and\nnull\u0020which\u0020mean\u0020the\u0020same\u0020\u0028although\u0020it\u0020should\u0020be\u0020noted\u0020that\u0020all\u0020quads\u0020in\nNamedNode\/BlankNode\u0020graphs\u0020also\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0029.",
            "url": "classes/rdfInterface-Quad.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithGraph\u0028\u0029",
            "name": "withGraph",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare",
            "name": "QuadCompare",
            "summary": "Interface\u0020allowing\u0020to\u0020compare\u0020Quads.",
            "url": "classes/rdfInterface-QuadCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator",
            "name": "QuadIterator",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace",
            "name": "RdfNamespace",
            "summary": "",
            "url": "classes/rdfInterface-RdfNamespace.html"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_remove"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_get"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_getAll"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_expand"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_shorten"
        },                {
            "fqsen": "\\rdfInterface\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serialize"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serializeStream"
        },                {
            "fqsen": "\\rdfInterface\\Term",
            "name": "Term",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Term.html"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare",
            "name": "TermCompare",
            "summary": "Description\u0020of\u0020TermCompare",
            "url": "classes/rdfInterface-TermCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-TermCompare.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-TermCompare.html#method___toString"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\termTemplates",
            "name": "termTemplates",
            "summary": "",
            "url": "namespaces/termtemplates.html"
        },                {
            "fqsen": "\\rdfInterface",
            "name": "rdfInterface",
            "summary": "",
            "url": "namespaces/rdfinterface.html"
        }            ]
);
