Search.appendIndex(
    [
                {
            "fqsen": "\\termTemplates\\AnyOfTemplate",
            "name": "AnyOfTemplate",
            "summary": "Description\u0020of\u0020AnyOfTemplate",
            "url": "classes/termTemplates-AnyOfTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\AnyOfTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-AnyOfTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\AnyOfTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-AnyOfTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\AnyOfTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-AnyOfTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\AnyOfTemplate\u003A\u003A\u0024terms",
            "name": "terms",
            "summary": "",
            "url": "classes/termTemplates-AnyOfTemplate.html#property_terms"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate",
            "name": "LiteralTemplate",
            "summary": "Description\u0020of\u0020LiteralTemplate",
            "url": "classes/termTemplates-LiteralTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-LiteralTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A\u0024lang",
            "name": "lang",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#property_lang"
        },                {
            "fqsen": "\\termTemplates\\LiteralTemplate\u003A\u003A\u0024datatype",
            "name": "datatype",
            "summary": "",
            "url": "classes/termTemplates-LiteralTemplate.html#property_datatype"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeTemplate",
            "name": "NamedNodeTemplate",
            "summary": "Description\u0020of\u0020AnyNamedNode",
            "url": "classes/termTemplates-NamedNodeTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-NamedNodeTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\NamedNodeTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-NamedNodeTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate",
            "name": "NotTemplate",
            "summary": "Provides\u0020condition\u0020negation",
            "url": "classes/termTemplates-NotTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-NotTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-NotTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-NotTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/termTemplates-NotTemplate.html#method_getGraph"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/termTemplates-NotTemplate.html#method_getObject"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/termTemplates-NotTemplate.html#method_getPredicate"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/termTemplates-NotTemplate.html#method_getSubject"
        },                {
            "fqsen": "\\termTemplates\\NotTemplate\u003A\u003A\u0024term",
            "name": "term",
            "summary": "",
            "url": "classes/termTemplates-NotTemplate.html#property_term"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate",
            "name": "NumericTemplate",
            "summary": "Description\u0020of\u0020AnyNamedNode",
            "url": "classes/termTemplates-NumericTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-NumericTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024numericTypes",
            "name": "numericTypes",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_numericTypes"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024fn",
            "name": "fn",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_fn"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024strict",
            "name": "strict",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_strict"
        },                {
            "fqsen": "\\termTemplates\\NumericTemplate\u003A\u003A\u0024fvalue",
            "name": "fvalue",
            "summary": "",
            "url": "classes/termTemplates-NumericTemplate.html#property_fvalue"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate",
            "name": "PredicateTemplate",
            "summary": "Description\u0020of\u0020QuadTemplate",
            "url": "classes/termTemplates-PredicateTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-PredicateTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_getSubject"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_getPredicate"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_getObject"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_getGraph"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_withSubject"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_withPredicate"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_withObject"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AwithGraph\u0028\u0029",
            "name": "withGraph",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_withGraph"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003AwithNegate\u0028\u0029",
            "name": "withNegate",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#method_withNegate"
        },                {
            "fqsen": "\\termTemplates\\PredicateTemplate\u003A\u003A\u0024tmpl",
            "name": "tmpl",
            "summary": "",
            "url": "classes/termTemplates-PredicateTemplate.html#property_tmpl"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate",
            "name": "QuadTemplate",
            "summary": "Description\u0020of\u0020QuadTemplate",
            "url": "classes/termTemplates-QuadTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-QuadTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getSubject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getPredicate"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getObject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_getGraph"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_withSubject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_withPredicate"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_withObject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AwithGraph\u0028\u0029",
            "name": "withGraph",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_withGraph"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003AwithNegate\u0028\u0029",
            "name": "withNegate",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#method_withNegate"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_subject"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024predicate",
            "name": "predicate",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_predicate"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_object"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024graph",
            "name": "graph",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_graph"
        },                {
            "fqsen": "\\termTemplates\\QuadTemplate\u003A\u003A\u0024negate",
            "name": "negate",
            "summary": "",
            "url": "classes/termTemplates-QuadTemplate.html#property_negate"
        },                {
            "fqsen": "\\termTemplates\\TermTemplatesException",
            "name": "TermTemplatesException",
            "summary": "Description\u0020of\u0020TermTemplatesException",
            "url": "classes/termTemplates-TermTemplatesException.html"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate",
            "name": "ValueTemplate",
            "summary": "Description\u0020of\u0020AnyNamedNode",
            "url": "classes/termTemplates-ValueTemplate.html"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#method___construct"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/termTemplates-ValueTemplate.html#method___toString"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#method_equals"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AEQUALS",
            "name": "EQUALS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_EQUALS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ANOT_EQUALS",
            "name": "NOT_EQUALS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_NOT_EQUALS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ASTARTS",
            "name": "STARTS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_STARTS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AENDS",
            "name": "ENDS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_ENDS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ACONTAINS",
            "name": "CONTAINS",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_CONTAINS"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AGREATER",
            "name": "GREATER",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_GREATER"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ALOWER",
            "name": "LOWER",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_LOWER"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AGREATER_EQUAL",
            "name": "GREATER_EQUAL",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_GREATER_EQUAL"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003ALOWER_EQUAL",
            "name": "LOWER_EQUAL",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_LOWER_EQUAL"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AANY",
            "name": "ANY",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_ANY"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003AREGEX",
            "name": "REGEX",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#constant_REGEX"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A\u0024fn",
            "name": "fn",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#property_fn"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#property_value"
        },                {
            "fqsen": "\\termTemplates\\ValueTemplate\u003A\u003A\u0024matchMode",
            "name": "matchMode",
            "summary": "",
            "url": "classes/termTemplates-ValueTemplate.html#property_matchMode"
        },                {
            "fqsen": "\\rdfInterface\\BlankNodeInterface",
            "name": "BlankNodeInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-BlankNodeInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface",
            "name": "DataFactoryInterface",
            "summary": "",
            "url": "classes/rdfInterface-DataFactoryInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003AnamedNode\u0028\u0029",
            "name": "namedNode",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020named\u0020node.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_namedNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003AblankNode\u0028\u0029",
            "name": "blankNode",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020blank\u0020node.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_blankNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003Aliteral\u0028\u0029",
            "name": "literal",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020literal.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_literal"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003AdefaultGraph\u0028\u0029",
            "name": "defaultGraph",
            "summary": "Returns\u0020an\u0020RDF\u0020default\u0020graph\u0020object.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_defaultGraph"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003Aquad\u0028\u0029",
            "name": "quad",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020quad.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_quad"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface",
            "name": "DatasetInterface",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-DatasetInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_factory"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "Returns\u0020a\u0020new\u0020dataset\u0020being\u0020a\u0020union\u0020of\u0020the\u0020current\u0020one\u0020and\u0020the\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "Returns\u0020a\u0020dataset\u0020being\u0020a\u0020symmetric\u0020difference\u0020of\u0020the\u0020current\u0020dataset\u0020and\nthe\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020quad\u0028s\u0029\u0020to\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_delete"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AdeleteExcept\u0028\u0029",
            "name": "deleteExcept",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_deleteExcept"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AforEach\u0028\u0029",
            "name": "forEach",
            "summary": "Iterates\u0020trough\u0020all\u0020quads\u0020replacing\u0020them\u0020with\u0020a\u0020callback\u0020result.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_forEach"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Checks\u0020if\u0020a\u0020given\u0020offset\u0020exists.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetExists"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Returns\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetGet"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Assigns\u0020a\u0020new\u0020value\u0020to\u0020the\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Removes\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetUnset"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aevery\u0028\u0029",
            "name": "every",
            "summary": "Checks\u0020if\u0020all\u0020quads\u0020in\u0020the\u0020dataset\u0020match\u0020a\u0020given\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_every"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Anone\u0028\u0029",
            "name": "none",
            "summary": "Checks\u0020if\u0020no\u0020quad\u0020in\u0020the\u0020dataset\u0020matches\u0020a\u0020given\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_none"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "Checks\u0020if\u0020any\u0020quad\u0020in\u0020the\u0020dataset\u0020matches\u0020a\u0020given\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_any"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_reduce"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistSubjects\u0028\u0029",
            "name": "listSubjects",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020subjects.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listSubjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistPredicates\u0028\u0029",
            "name": "listPredicates",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020predicates.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listPredicates"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistObjects\u0028\u0029",
            "name": "listObjects",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020objects.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listObjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistGraphs\u0028\u0029",
            "name": "listGraphs",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020graphs.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listGraphs"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "Fetches\u0020subject\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "Fetches\u0020subject\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "Fetches\u0020object\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "Fetches\u0020graph\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetSubjectValue\u0028\u0029",
            "name": "getSubjectValue",
            "summary": "Returns\u0020result\u0020of\u0020calling\u0020the\u0020getValue\u0028\u0029\u0020method\u0020on\u0020a\u0020subject\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getSubjectValue"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetPredicateValue\u0028\u0029",
            "name": "getPredicateValue",
            "summary": "Returns\u0020result\u0020of\u0020calling\u0020the\u0020getValue\u0028\u0029\u0020method\u0020on\u0020a\u0020subject\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getPredicateValue"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetObjectValue\u0028\u0029",
            "name": "getObjectValue",
            "summary": "Returns\u0020result\u0020of\u0020calling\u0020the\u0020getValue\u0028\u0029\u0020method\u0020on\u0020a\u0020subject\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getObjectValue"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AgetGraphValue\u0028\u0029",
            "name": "getGraphValue",
            "summary": "Returns\u0020result\u0020of\u0020calling\u0020the\u0020getValue\u0028\u0029\u0020method\u0020on\u0020a\u0020subject\u0020of\u0020a\u0020first\u0020quad\u0020matching\u0020a\u0020given\u0020filter\u0020or\u0020null\u0020if\u0020no\u0020quad\u0020matches\u0020the\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_getGraphValue"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface",
            "name": "DatasetNodeInterface",
            "summary": "Node\u002Doriented\u0020graph\u0020API\u0020interface.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "Creates\u0020a\u0020DatasetNodeInterface\u0020object.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_factory"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AgetDataset\u0028\u0029",
            "name": "getDataset",
            "summary": "The\u0020actual\u0020dataset\u0020\u0028and\u0020not\u0020its\u0020copy\u0029\u0020should\u0020be\u0020returned.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_getDataset"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AgetNode\u0028\u0029",
            "name": "getNode",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_getNode"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AwithDataset\u0028\u0029",
            "name": "withDataset",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_withDataset"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AwithNode\u0028\u0029",
            "name": "withNode",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_withNode"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020quad\u0028s\u0029\u0020to\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Assigns\u0020a\u0020new\u0020value\u0020to\u0020the\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "Only\u0020those\u0020quads\u0020from\u0020\u0024other\u0020which\u0020have\u0020subject\u0020matching\u0020the\u0020DatasetNodeInterface\u0027s\u0020node\u0020are\u0020added.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "The\u0020resulting\u0020dataset\u0020should\u0020contain\u003A\n\u002D\u0020all\u0020quads\u0020of\u0020the\u0020DatasetNodeInterface\u0020with\u0020subject\u0020other\u0020than\u0020the\u0020node\n\u002D\u0020xor\u0020between\u0020triples\u0020of\u0020the\u0020DatasetNodeInterface\u0020with\u0020subject\u0020being\u0020the\u0020node\n\u0020\u0020and\u0020triples\u0020of\u0020the\u0020\u0024other\u0020with\u0020subject\u0020being\u0020the\u0020node",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "Quads\u0020with\u0020subject\u0020other\u0020than\u0020DatasetNodeInterface\u0027s\u0020node\u0020should\u0020be\nreturned\u0020untouched.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraphInterface",
            "name": "DefaultGraphInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-DefaultGraphInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraphInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-DefaultGraphInterface.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface",
            "name": "LiteralInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-LiteralInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020literal\u0027s\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AgetLang\u0028\u0029",
            "name": "getLang",
            "summary": "Returns\u0020literal\u0027s\u0020language\u0020tag.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_getLang"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AgetDatatype\u0028\u0029",
            "name": "getDatatype",
            "summary": "Returns\u0020literal\u0027s\u0020datatype.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_getDatatype"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AwithValue\u0028\u0029",
            "name": "withValue",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020given\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_withValue"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AwithLang\u0028\u0029",
            "name": "withLang",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020lang\u0020tag\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_withLang"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AwithDatatype\u0028\u0029",
            "name": "withDatatype",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020with\u0020this\u0020one\u0020with\u0020datatype\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_withDatatype"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003ACAST_LEXICAL_FORM",
            "name": "CAST_LEXICAL_FORM",
            "summary": "",
            "url": "classes/rdfInterface-LiteralInterface.html#constant_CAST_LEXICAL_FORM"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003ACAST_DATATYPE",
            "name": "CAST_DATATYPE",
            "summary": "",
            "url": "classes/rdfInterface-LiteralInterface.html#constant_CAST_DATATYPE"
        },                {
            "fqsen": "\\rdfInterface\\MultipleQuadsMatchedException",
            "name": "MultipleQuadsMatchedException",
            "summary": "Specialization\u0020of\u0020the\u0020\\UnexpectedValueException\u0020indicating\u0020multiple\u0020quads\nmatch\u0020while\u0020accessing\u0020a\u0020DatasetInterface\u0020object\u0020using\u0020the\u0020ArrayAccess\u0020syntax\n\u0028\u0024dataset\u005Boffset\u005D\u0029",
            "url": "classes/rdfInterface-MultipleQuadsMatchedException.html"
        },                {
            "fqsen": "\\rdfInterface\\NamedNodeInterface",
            "name": "NamedNodeInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-NamedNodeInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface",
            "name": "ParserInterface",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html#method_parse"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html#method_parseStream"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface",
            "name": "QuadCompareInterface",
            "summary": "Interface\u0020allowing\u0020to\u0020compare\u0020Quads.",
            "url": "classes/rdfInterface-QuadCompareInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface",
            "name": "QuadInterface",
            "summary": "Extends\u0020Term\u0020because\u0020of\u0020RDF\u002A",
            "url": "classes/rdfInterface-QuadInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "Null\u0020is\u0020not\u0020allowed\u0020to\u0020deal\u0020with\u0020the\u0020ambiguity\u0020between\u0020DefaultGraph\u0020and\nnull\u0020which\u0020mean\u0020the\u0020same\u0020\u0028although\u0020it\u0020should\u0020be\u0020noted\u0020that\u0020all\u0020quads\u0020in\nNamedNode\/BlankNode\u0020graphs\u0020also\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0029.",
            "url": "classes/rdfInterface-QuadInterface.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithGraph\u0028\u0029",
            "name": "withGraph",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorAggregateInterface",
            "name": "QuadIteratorAggregateInterface",
            "summary": "Description\u0020of\u0020QuadIteratorAggregateInterface",
            "url": "classes/rdfInterface-QuadIteratorAggregateInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorAggregateInterface\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "Returns\u0020QuadIteratorInterface\u0020iterating\u0020over\u0020dataset\u0027s\u0020quads.",
            "url": "classes/rdfInterface-QuadIteratorAggregateInterface.html#method_getIterator"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorInterface",
            "name": "QuadIteratorInterface",
            "summary": "",
            "url": "classes/rdfInterface-QuadIteratorInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorInterface\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-QuadIteratorInterface.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface",
            "name": "RdfNamespaceInterface",
            "summary": "",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_remove"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_get"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_getAll"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_expand"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_shorten"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface",
            "name": "SerializerInterface",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html#method_serialize"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html#method_serializeStream"
        },                {
            "fqsen": "\\rdfInterface\\TermCompareInterface",
            "name": "TermCompareInterface",
            "summary": "Description\u0020of\u0020TermCompare",
            "url": "classes/rdfInterface-TermCompareInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\TermCompareInterface\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-TermCompareInterface.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermCompareInterface\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Should\u0020return\u003A",
            "url": "classes/rdfInterface-TermCompareInterface.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\TermInterface",
            "name": "TermInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-TermInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\TermInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfInterface-TermInterface.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface",
            "name": "TermIteratorInterface",
            "summary": "",
            "url": "classes/rdfInterface-TermIteratorInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-TermIteratorInterface.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface\u003A\u003Acontains\u0028\u0029",
            "name": "contains",
            "summary": "",
            "url": "classes/rdfInterface-TermIteratorInterface.html#method_contains"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface\u003A\u003Askip\u0028\u0029",
            "name": "skip",
            "summary": "",
            "url": "classes/rdfInterface-TermIteratorInterface.html#method_skip"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface\u003A\u003Aintersect\u0028\u0029",
            "name": "intersect",
            "summary": "",
            "url": "classes/rdfInterface-TermIteratorInterface.html#method_intersect"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "Extracts\u0020values\u0020of\u0020all\u0020terms\u0020and\u0020returns\u0020them\u0020as\u0020an\u0020array.",
            "url": "classes/rdfInterface-TermIteratorInterface.html#method_getValues"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\termTemplates",
            "name": "termTemplates",
            "summary": "",
            "url": "namespaces/termtemplates.html"
        },                {
            "fqsen": "\\rdfInterface",
            "name": "rdfInterface",
            "summary": "",
            "url": "namespaces/rdfinterface.html"
        }            ]
);
